import * as R from 'rambda';

export {default as assocPath} from './modules/assocPath'
export {default as compact} from './modules/compact'
export {default as composeAsync} from './modules/composeAsync'
export {default as debounce} from './modules/debounce'
export const DELAY = 'RAMBDAX_DELAY'
export {default as delay} from './modules/delay'
export {default as debug} from './modules/debug'
export {default as evolve} from './modules/evolve'
export {default as greater} from './modules/greater'
export {default as ifElseAsync} from './modules/ifElseAsync'
export {default as intersection} from './modules/intersection'
export {default as isPromiseLike} from './modules/isPromiseLike'
export {default as isValid} from './modules/isValid'
export {default as less} from './modules/less'
export {default as mapAsync} from './modules/mapAsync'
export {default as mapFastAsync} from './modules/mapFastAsync'
export {default as memoize} from './modules/memoize'
export {default as mergeAll} from './modules/mergeAll'
export {default as omitBy} from './modules/omitBy'
export {default as once} from './modules/once'
export {default as pickBy} from './modules/pickBy'
export {default as produce} from './modules/produce'
export {default as random} from './modules/random'
export {default as rangeBy} from './modules/rangeBy'
export {default as renameProps} from './modules/renameProps'
export {default as resolve} from './modules/resolve'
export {default as resolveSecure} from './modules/resolveSecure'
export {default as shuffle} from './modules/shuffle'
export {default as tapAsync} from './modules/tapAsync'
export {default as throttle} from './modules/throttle'
export {default as tryCatch} from './modules/tryCatch'
export {default as when} from './modules/when'
export {default as where} from './modules/where'

// Follows code generated by `run rambda`
export const always = R.always
export const complement = R.complement
export const F = R.F
export const identity = R.identity
export const not = R.not
export const T = R.T
export const trim = R.trim
export const add = R.add
export const addIndex = R.addIndex
export const adjust = R.adjust
export const all = R.all
export const allPass = R.allPass
export const anyPass = R.anyPass
export const any = R.any
export const append = R.append
export const both = R.both
export const compose = R.compose
export const concat = R.concat
export const contains = R.contains
export const curry = R.curry
export const dec = R.dec
export const defaultTo = R.defaultTo
export const divide = R.divide
export const drop = R.drop
export const dropLast = R.dropLast
export const either = R.either
export const endsWith = R.endsWith
export const inc = R.inc
export const equals = R.equals
export const filter = R.filter
export const find = R.find
export const findIndex = R.findIndex
export const flatten = R.flatten
export const flip = R.flip
export const forEach = R.forEach
export const has = R.has
export const head = R.head
export const ifElse = R.ifElse
export const is = R.is
export const isNil = R.isNil
export const includes = R.includes
export const indexOf = R.indexOf
export const init = R.init
export const join = R.join
export const lastIndexOf = R.lastIndexOf
export const last = R.last
export const length = R.length
export const map = R.map
export const match = R.match
export const merge = R.merge
export const modulo = R.modulo
export const multiply = R.multiply
export const none = R.none
export const omit = R.omit
export const partialCurry = R.partialCurry
export const path = R.path
export const pathOr = R.pathOr
export const pick = R.pick
export const pickAll = R.pickAll
export const pipe = R.pipe
export const pluck = R.pluck
export const prepend = R.prepend
export const prop = R.prop
export const propEq = R.propEq
export const range = R.range
export const reduce = R.reduce
export const reject = R.reject
export const repeat = R.repeat
export const replace = R.replace
export const reverse = R.reverse
export const sort = R.sort
export const sortBy = R.sortBy
export const split = R.split
export const splitEvery = R.splitEvery
export const startsWith = R.startsWith
export const subtract = R.subtract
export const tap = R.tap
export const tail = R.tail
export const take = R.take
export const takeLast = R.takeLast
export const test = R.test
export const times = R.times
export const toLower = R.toLower
export const toUpper = R.toUpper
export const toString = R.toString
export const type = R.type
export const uniq = R.uniq
export const update = R.update
export const values = R.values
export const without = R.without