const fs = require('fs-extra')
const path = require('path')
const R = require('rambda')

const generateRambdaExports = () => {
  const separator = '//Follows code generated by `run rambda`'
  const filePath = path.resolve(__dirname, '../../rambdax.js')
  const rambdaxContent = R.compose(
    R.append(separator),
    R.head,
    R.split(separator)
  )(fs.readFileSync(filePath).toString())

  const content = R.compose(
    R.join('\n'),
    R.prepend(rambdaxContent),
    R.map(x => `export const ${ x } = R.${ x }`),
    R.filter(x => x !== 'is'),
    //TODO
    //R.filter(R.not('is')),
  )(Object.keys(R))

  fs.writeFileSync(filePath, content)

  console.log('done')
}

generateRambdaExports()
